// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBblSOtemWf9OCynUKW_bA2wQr5Jaig0V4',
    appId: '1:330800846396:web:22173c6f49905caaa99539',
    messagingSenderId: '330800846396',
    projectId: 'culturals-d02fb',
    authDomain: 'culturals-d02fb.firebaseapp.com',
    storageBucket: 'culturals-d02fb.appspot.com',
    measurementId: 'G-0X081N32JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-rPKSvkgUCweEQypUOFErVGlIfRBlYfw',
    appId: '1:330800846396:android:75b83cb1b19265d3a99539',
    messagingSenderId: '330800846396',
    projectId: 'culturals-d02fb',
    storageBucket: 'culturals-d02fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCKarbHSs2Jdn7HrQhzjffjt5XC_JnxQs',
    appId: '1:330800846396:ios:f01be0731835c75ea99539',
    messagingSenderId: '330800846396',
    projectId: 'culturals-d02fb',
    storageBucket: 'culturals-d02fb.appspot.com',
    iosBundleId: 'com.example.safezone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCKarbHSs2Jdn7HrQhzjffjt5XC_JnxQs',
    appId: '1:330800846396:ios:fc50e0b50d0744e5a99539',
    messagingSenderId: '330800846396',
    projectId: 'culturals-d02fb',
    storageBucket: 'culturals-d02fb.appspot.com',
    iosBundleId: 'com.example.safezone.RunnerTests',
  );
}
